

eureka:
  instance:
    hostname: https://config-sulluscocha.herokuapp.com/
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka
server:
  port: 0
