spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asdrian44/configserver
server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka/
