

eureka:
  instance:
    hostname: https://config-sulluscocha.herokuapp.com/
    non-secure-port: 80
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka
server:
  port: 0

spring:
  application:
    name: config-server
