spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/asdrian44/configserver
server:
  port: 0


eureka:
  instance:
    hostname: ${APP_NAME}.heroku.com
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka/
    fetch-registry: true
    register-with-eureka: true

