spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asdrian44/configserver
server:
  port: 8888


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka
