eureka:
  instance:
    nonSecurePort: 80
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka
server:
  port: 0

spring:
  application:
    name: config-server

